# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'
    
# Add/remove 'waiting' label if issue contains the word 'waiting'
waiting:
    - 'waiting'
